##.properties
#spring.datasource.url = jdbc:postgresql://db.gejqpspppereuemgbisl.supabase.co:5432/postgres
#spring.datasource.uername = postgres
#spring.datasource.password=
#yml ??? ??. ???? ??
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
            #Test
      springframework :
        security : debug

auth:
  jwt:
    issuer : team.sparta.com
    secret : gH7kRw9FpD3yN2mQxL5aJcUvZ1oP4bS6
    accessTokenExpirationHour : 168